apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-certificate
  namespace: karatsuba
spec:
  secretName: bitwarden-ssl-secret
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - password.karatsubalabs.com
