apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitbounties-certificate
  namespace: karatsuba
spec:
  secretName: gitbounties-ssl-secret
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - gitbounties.karatsubalabs.com
